typography_spectrum: 0.5372415871825069
color:
  brandColors:
    - '#ffffff'
    - '#37365a'
    - '#9e2937'
    - '#787878'
    - '#c79399'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2854405171237886
analytics:
  google: null
  facebook: null
  twitter: null
name: NovussUSA
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: You have to beat the best to be the best!!!
purpose: []
