typography_spectrum: 0.5372415871825069
color:
  brandColors:
    - '#ffffff'
    - '#37365a'
    - '#9e2937'
    - '#787878'
    - '#c79399'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2854405171237886
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/93aa4853-a87a-4cda-adf2-d3f06d906575.jpg
name: American Novuss Association
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5aba13c-b525-4b1a-b8bb-af9926d9b30c.png
title: You have to Beat the Best to be the Best!!!
description: Welcome to American Novuss Association
purpose: []
