name: NovussUSA
favicon: null
layout_spectrum: 0.2854405171237886
typography_spectrum: 0.5372415871825069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#37365a'
    - '#9e2937'
    - '#787878'
    - '#c79399'
  brandStrength: 0.3125
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5263085749465972
purpose: []
